version: '3.3'
services:
  db:
    image: postgres:16
    container_name: nest-bp-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest-bp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:3001:${HTTP_PORT}'
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: nest-bp-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  loki:
    image: grafana/loki:2.9.8
    container_name: nest-bp-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki:/loki

  promtail:
    image: grafana/promtail:2.9.8
    container_name: nest-bp-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./monitoring/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - ./logs:/var/log/app
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.2
    container_name: nest-bp-grafana
    restart: unless-stopped
    ports:
      - '127.0.0.1:3002:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana:/var/lib/grafana
      - ./monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./monitoring/grafana:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
      - loki


volumes:
  db:
  node_modules:
  grafana:
  loki:
